repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-builtin-literals
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-case-conflict

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
